INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Romario', 5 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Bebeto', 3 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Taffarel', 2 , 2)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Rogerio Ceni', 1 , 2)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Ronaldo', 8 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Rivaldo', 9 , 4)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Cafu', 7 , 5)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Leonardo', 4 , 5)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Dunga', 6 , 6)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Zetti', 10 , 2)
	
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Ronaldinho', 5 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Romarinho', 3 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Ribamar', 2 , 2)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Tufão', 1 , 2)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Adriano', 8 , 1)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Coutinho', 9 , 4)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Pato', 7 , 5)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Cleiton', 4 , 5)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Jefferson', 6 , 6)
INSERT INTO Jogador(Nome, ClubeId, PosicaoId) VALUES('Danilo', 10 , 2)