INSERT INTO Clube(Nome, Pontos) VALUES('Sao Paulo', 80)
INSERT INTO Clube(Nome, Pontos) VALUES('Corinthians', 60)
INSERT INTO Clube(Nome, Pontos) VALUES('Palmeiras', 60)
INSERT INTO Clube(Nome, Pontos) VALUES('Botafogo', 40)
INSERT INTO Clube(Nome, Pontos) VALUES('Vasco', 40)
INSERT INTO Clube(Nome, Pontos) VALUES('Flamengo', 60)
INSERT INTO Clube(Nome, Pontos) VALUES('Santos', 70)
INSERT INTO Clube(Nome, Pontos) VALUES('Bahia', 80)
INSERT INTO Clube(Nome, Pontos) VALUES('Gremio', 60)
INSERT INTO Clube(Nome, Pontos) VALUES('Internacional', 80)